package com.backend.project.repository;

import com.backend.project.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Spring Data JPA Repository for User entity.
 * JpaRepository provides out-of-the-box methods:
 * save(), findById(), findAll(), deleteById(), count() etc.
 */
@Repository
public interface UserRepository extends JpaRepository<User, Long> {

    // Derived Query method generated by Spring Data JPA
    Optional<User> findByUsername(String username);

    boolean existsByUsername(String username);

    boolean existsByEmail(String email);
}
