# Server configuration
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_demo_db
spring.datasource.username=postgres
spring.datasource.password=guru@2305
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
# 'update' automatically creates/updates database tables based on your Java @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration (256-bit Base64 secret key)
jwt.secret=QkU1NzM3NjFBNzY5N0Y2RDYyNTE2NTU0Njg1NzZEQjU0RTc4NTg2ODVFNzMyRjQxM0Y0NDI4NDcyQjRCNjJQNQ==
jwt.expiration-ms=86400000
